### ISSUE TITLE
Help with ULTRA-CSA queries

### ISSUE THREAD

**Issue by Abdallah-Abuaisha** [kit-algo/ULTRA#25]
Greetings! I need some guidance on how to run ULTRA-CSA queries using the provided networks (e.g., London and Switzerland). Specifically, when using the command runULTRACSAQueries in the ./ULTRA application, which files should be used as inputs?

My understanding is as follows:
1) For "CSA input file", I first converted the "intermediate.binary" file located in London/Walking/**Full** to "csa.binary" file using the "intermediateToCSA" command in ./Network application. I then used this file as the first argument. 
2) For the "CH data", I used the CH files found in London/Walking/**Contracted** (i.e., London/Walking/Contracted/**ch**).

Is that the correct way to run ULTRA-CSA queries?

When I follow this process, I sometimes encounter errors (e.g., "segmentation fault" or "bus error"), while at other times, it seems to work but takes longer than expected, and the runtimes do not seem right (e.g., for London I get ~**155**ms initialisation and ~2.5ms scan!).  

P.S. I am using a Mac M1 machine which does not support OpenMP. I used **libomp** instead and made some changes to the MultiThreading.h file to compile without errors. However, I don't think this has anything to do with running queries with the provided networks without any preprocessing. Please correct me if I am wrong.

Also, is there any relevance of the London/Original directory in this context? What does it actually represent? 

Apologies for the lengthy post.

Thank you!

**Comment by jonas-sauer** [comment]
It seems that you did not run the preprocessing steps that are needed for ULTRA-CSA. The files we provide do not include the output of these steps, so you have to create them yourself like this:

1. Run `intermediateToCSA` with input file `London/Walking/Full/intermediate.binary` and output file `London/Walking/Full/csa.binary`.
2. Run `computeStopToStopShortcuts` with input file `London/Walking/Contracted/raptor.binary` and output file `London/Walking/Shortcuts/raptor.binary`.
3. The produced output is in RAPTOR format. You need to convert this to CSA format manually: Copy `London/Walking/Full/csa.binary` to `London/Walking/Shortcuts/csa.binary`. Then rename all the `London/Walking/Shortcuts/raptor.binary.graph.*` files to `csa.binary.graph.*.
4. Run `buildCH` with input file London/Walking/Full/csa.binary.graph` and output file `London/Walking/CH/ch`.
5. Run `runULTRACSAQueries` with CSA input file `London/Walking/Shortcuts/csa.binary` and CH data London/Walking/CH/ch`.

As for the `London/Original` directory, this is the original public transit network as retrieved from Transport for London, without the OpenStreetMap footpath graph.

**Comment by Abdallah-Abuaisha** [comment]
Thank you @jonas-sauer  for your detailed response. I followed the procedure, and it now works perfectly well, producing reasonable results.
